### ISSUE TITLE
Feature request: add custom tags with system values (ie for adding Date)

### ISSUE THREAD

**Issue by og1** [Servoy/smartDocumentEditor#4]
Can I add a tag for inserting the date in the Tag Builder?

**Comment by rvanveen-servoy** [comment]
Hi,

The tags are bound to record values, so to have this there are some options:

1. Add a calculation that is returning the current date
2. Add a tag overwrite function so that code will be called where you can add your own return value.

To give a sample to the 2nd option.
What you can do is in the mergeTag call add a function to the 5e param.
`EDITOR_INSTANCE.mergeTags(foundset.getSelectedRecord(), true, 'youCantFindMe', ifParser, mentionOverwrite, repeatOverwrite);`

in this case the function mentionOverwrite.
That function will then be called for every mention if find while parsing the document.

My function is containing this:
`function mentionOverwrite(dataprovider, relation, record, value, mentionRealvalue, mentionDisplayValue) {
	application.output('Document mentionCallback -  value: `' + value + "` dataprovider: `" + dataprovider + "` relationName: `" + relation + "` record: `" + record + "` mentionRealValue: `" + mentionRealvalue + "`");
	if (dataprovider === 'calculation_number') {
		return 10000;
	}
	return value;
}`

So in this case i overwrite the real value with the mentionOverwrite.
What means in this case it is always returning 10000 for calculation_number.
For the others it is just returning the value as it should be (from the record).
